server:
  port: 8080

spring:
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-rds.cuwguiwtvuh1.ap-northeast-2.rds.amazonaws.com:3306/sport_result
    username: tkppp
    password: tiffndla0423
  jpa:
    hibernate:
      ddl-auto: update

